Repository MercsClan/mercchan, pull requests merged in 2020-08, with the labels that each got.

#18 Reboot and Kill Commands
  commands/utilities/kill.js
  commands/utilities/reboot.js
Labels: enhancement

#19 Added event command, fixed reboot
  README.md
  commands/other/event.js
  commands/utilities/reboot.js
Labels: enhancement, help wanted

#20 Natedev
  .gitignore
  Firebase/firebase.js
  commands/other/event.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#21 Events command - fixed embed message
  commands/other/event.js
Labels: bug

#22 Updated !events to create role and text channel
  commands/other/event.js
Labels: enhancement

#23 Added Commands: Purge, Humble, Updating RocketLeague
  commands/games/rocketleague.js
  commands/other/humble.js
  commands/utilities/purge.js
  package-lock.json
  package.json
  utils/RocketLeague.js
  utils/working.json
Labels: enhancement

#24 Fixed Events role adding
  commands/games/rocketleague.js
  commands/other/event.js
  utils/RocketLeague.js
Labels: bug

#26 !event sends role ID and channel ID to firebase
  commands/other/event.js
  utils/eventCleanup.js
Labels: enhancement

#28 Created Event Handler, cleaned up index.js, added OS Hostname on startup to audit log
  events/ready.js
  events/voiceStateUpdate.js
  index.js
Labels: enhancement

#29 moved events to a folder, added cleanevents
  commands/events/cleanevents.js
  commands/events/event.js
  index.js
  utils/eventCleanup.js
Labels: enhancement

#30 Updated Readme
  README.md
  commands/events/cleanevents.js
  commands/utilities/purge.js
  utils/RocketLeague.js
Labels: bug, documentation

#32 Natedev
  commands/utilities/kill.js
  commands/utilities/reboot.js
  utils/RocketLeague.js
Labels: bug

#33 Added roll command
  commands/games/rocketleague.js
  commands/other/deal.js
  commands/other/weather.js
  commands/rpg/roll.js
  commands/utilities/kill.js
  commands/utilities/reboot.js
  index.js
Labels: enhancement

#34 added coinflip command
  commands/rpg/coinflip.js
Labels: enhancement

#36 announcement command and updated readme
  .env.example
  README.md
  commands/admin/kill.js
  commands/admin/purge.js
  commands/admin/reboot.js
  commands/admin/say.js
  commands/events/cleanevents.js
  commands/events/event.js
  index.js
Labels: documentation, enhancement

#38 Fixed Play Permissions
  commands/admin/kill.js
  commands/admin/reboot.js
  commands/admin/say.js
  commands/music/play.js
  commands/rpg/coinflip.js
  commands/rpg/createcharacter.js
Labels: bug

#39 Fixed Permissions on music commands
  commands/music/leave.js
  commands/music/skip.js
  commands/music/skipto.js
Labels: bug

#40 Added characterlist, renamed charactercreate
  README.md
  commands/rpg/charactercreate.js
  commands/rpg/characterlist.js
Labels: RPG, enhancement

#41 Added guildCreate, guildMemberAdd, cleaned up events import
  events/guildCreate.js
  events/guildMemberAdd.js
  events/voiceStateUpdate.js
  index.js
Labels: enhancement

#42 Added Message Collector for new Games channels
  events/messageReactionAdd.js
  events/messageReactionRemove.js
  index.js
Labels: enhancement

#43 Added Pause and Resume (same command) for Music Control
  README.md
  commands/music/pause.js
  index.js
Labels: enhancement
